### ISSUE TITLE
PowerShellExecutor.execute() waits forever when command fails

### ISSUE THREAD

**Issue by daveloyall** [frimtec/jpse#22]
Hi.  I'm using JPSE 1.2.0.  I'm running under OpenJDK 11.0.9.1_1 (from adoptopenjdk.net) on Windows Server 2008 R2.  (Yes, that machine will be decommissioned soon.)

My code looks like this:

```java
PowerShellExecutor executor = PowerShellExecutor.instance();
ExecutionResult results = executor.execute("Start-ScheduledTask -TaskName \"LogShippingFailure\"");
String stdout = results.getStandardOutput();
String stderr = results.getErrorOutput();
String errorcode = Integer.toString(results.getReturnCode());
```

When it runs, execution "never" reaches line three.  (I terminated it after waiting a minute.)

Here is a thread dump...

```
"http-nio-18080-exec-4" Id=31 cpu=15600100 ns usr=15600100 ns blocked 0 for -1 ms waited 2 for -1 ms
   java.lang.Thread.State: WAITING
	locks java.util.concurrent.ThreadPoolExecutor$Worker@21a5fd96
	at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
	- waiting on (a java.util.concurrent.CountDownLatch$Sync@5692145d)
	at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
	at java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1039)
	at java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
	at java.base@11.0.9.1/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
	at com.github.frimtec.libraries.jpse.StreamGobbler.waitTillFinished(StreamGobbler.java:28)
	at com.github.frimtec.libraries.jpse.WindowsPowerShellExecutor.execute(WindowsPowerShellExecutor.java:96)
	at com.github.frimtec.libraries.jpse.WindowsPowerShellExecutor.execute(WindowsPowerShellExecutor.java:44)
	at us.ne.state.ocio.server2server.Util.sendLogShippingFailureEvent(Util.java:33)
	at us.ne.state.ocio.server2server.NotifyLogShippingFailure.doGet(NotifyLogShippingFailure.java:21)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:880)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1601)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	- locked (a org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@5855f127) index 30 frame org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)
```

Part of the problem is that the command I provided is NOT valid on Windows Server 2008 R2.  When I try to run the command in a PowerShell prompt, I get this:

```
PS C:\Users\daveloyall> Start-ScheduledTask -TaskName "LogShippingFailure"
The term 'Start-ScheduledTask' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:20
+ Start-ScheduledTask <<<<  -TaskName "LogShippingFailure"
    + CategoryInfo          : ObjectNotFound: (Start-ScheduledTask:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Ok, fine... I will change my command to something valid.  But...

JPSE should report the error instead of hanging forever!

The problem has something to do with my Windows version or my PowerShell version.  Why?  Because when run the same code (modified to be an invalid PowerShell command) on a Windows 10 workstation, it does not wait forever.  It gives an error message (I see it in `results.getErrorOutput()`.)

Since the problem only happens on an end-of-life version of Windows, maybe it does not need to be fixed.  But, please consider making the code fail immediately and provide an error message.  It took some time for me to find the problem.

I hope this is helpful.

**Comment by frimtec** [comment]
Thank's a lot for your detaild report. I will have a closer look as soon as possible.

**Comment by frimtec** [comment]
I tried to reproduce your problem, but unfortunately I can't.

I used the following test code:
```
public class JpseTest {
  public static void main(String[] args) {
    PowerShellExecutor executor = PowerShellExecutor.instance();
    ExecutionResult results = executor.execute("Unknown-Command");
    String stdout = results.getStandardOutput();
    String stderr = results.getErrorOutput();
    String errorcode = Integer.toString(results.getReturnCode());
    System.out.println("errorcode = " + errorcode);
    System.out.println("stdout = " + stdout);
    System.out.println("stderr = " + stderr);
  }
```

The output comes immediatly:
```
errorcode = 1
stdout = 
stderr = #< CLIXML
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><S S="Error">Unknown-Command : The term 'Unknown-Command' is not recognized as the name of a cmdlet, function, script file, or _x000D__x000A_</S><S S="Error">operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try _x000D__x000A_</S><S S="Error">again._x000D__x000A_</S><S S="Error">At line:1 char:1_x000D__x000A_</S><S S="Error">+ Unknown-Command_x000D__x000A_</S><S S="Error">+ ~~~~~~~~~~~~~~~_x000D__x000A_</S><S S="Error">    + CategoryInfo          : ObjectNotFound: (Unknown-Command:String) [], CommandNotFoundException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : CommandNotFoundException_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>
```

The output in Powershell if executed directly is as follows and looks similar to your error output:
```
PS C:\Users\tkf9m> Unknown-Command
Unknown-Command : The term 'Unknown-Command' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ Unknown-Command
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Unknown-Command:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I'm using Windows 10, openjdk 11.0.9. and PowerShell 5.1.17763.1490.

**Comment by daveloyall** [comment]
frimtec, thanks for checking.  I was using PowerShell 2.0.  I upgraded to PowerShell 3.0 (still using the Win 2008 R2 machine) and now I can't reproduce the error either!  I now get similar results to what you get on Win10 + PS 5.1.17763.1490.

(Unfortunately, the cmdlet I wanted is still not available: it just isn't available on Windows 2008 R2, regardless of PowerShell version.  A helpful user said: "the biggest 'problem' with those new commands is that the CIM classes themselves are deployed only with the new OS releases".  So, I'm going to have to invoke schtasks.exe instead.)

**Comment by frimtec** [comment]
Thanks Dave for your feedback.

I guess I can not really help further with your issue. Seems that the hangers were due to the old powershell version.
I will close the ticket for now.
